### ISSUE TITLE
KeyError: 'openaccess'

### ISSUE THREAD

**Issue by Keramatfar** [scopus-api/scopus#100]
Hi,
I am working with this package to get data of some authors. I got this error for some authors in a loop that get information of each author.

     80                       pageRange=item.get('prism:pageRange'),
     81                       citedby_count=item.get('citedby-count'),
---> 82                       openaccess=item['openaccess'])
     83             out.append(new)
     84         return out

KeyError: 'openaccess'

So, i tried to remove that line, because i did not need that, but again the same error happened.

**Comment by Michael-E-Rose** [comment]
Hi @Keramatfar ! Could you give me code that lead to this error, please?

**Comment by Keramatfar** [comment]
Yes, Full Error:

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-6ae9d49a1a10> in <module>()
      3     print(num)
      4     search = scopus.ScopusSearch('AU-ID({0}) AND PUBYEAR AFT 2013'.format(au_ids[num]))
----> 5     df = pd.DataFrame(search.results)
      6     try:
      7         df['citedby_count'] = df['citedby_count'].astype(int)

D:\soft\Ins\anac\lib\site-packages\scopus\scopus_search.py in results(self)
     80                       pageRange=item.get('prism:pageRange'),
     81                       citedby_count=item.get('citedby-count'),
---> 82                       openaccess=item['openaccess'])
     83             out.append(new)
     84         return out

KeyError: 'openaccess'`

`for num in range(len(au_names)):
    print(num)
    search = scopus.ScopusSearch('AU-ID({0}) AND PUBYEAR AFT 2013'.format(au_ids[num]))
    df = pd.DataFrame(search.results)`

It should be noted that au_ids is a list of authors' ids in Scopus.

**Comment by Michael-E-Rose** [comment]
This doesn't help me. I need the author ID to replicate the error.
Print the author ID in each loop and then give me the author ID printed last.

**Comment by Michael-E-Rose** [comment]
KeyErrors are usually solved by reloading, see https://scopus.readthedocs.io/en/latest/tips.html#keyerror-eid
