### ISSUE TITLE
Possibility to use api key without config file

### ISSUE THREAD

**Issue by Blake11** [scopus-api/scopus#101]
Would it be possible to change the way api keys are used?
It would be beneficial for threaded application where api keys change based on a criteria in different threads.
Also this would reduce the number or disk reads/writes in some scenarios 

Expected usage:
 ```
key = "foo"
author = AuthorRetrieval(author_id, refresh=True, api_key=key)
```

**Comment by Michael-E-Rose** [comment]
This can be achieved like so:

```
from scopus import config, AuthorRetrieval
from scopus.exception import Scopus429Error

try:
    author = AuthorRetrieval(author_id, refresh=True)
exept Scopus429Error:
    config["Authentication"]["APIKey"] = "foo"
    author = AuthorRetrieval(author_id, refresh=True)
```
This will set the API key to be used w/o changing the configuration file.

**Comment by Blake11** [comment]
That is exactly what I was looking for. 
It should be included in documentation https://scopus.readthedocs.io/en/stable/configuration.html

**Comment by Michael-E-Rose** [comment]
https://pybliometrics.readthedocs.io/en/stable/tips.html#download-machine
