### ISSUE TITLE
KeyError for AuthorRetrieval.journal_history

### ISSUE THREAD

**Issue by Blake11** [scopus-api/scopus#102]
There is a KeyError("sourcetitle") on the journal_history property of AuthorRetrieval for the author with id '6508081477'.
There are some other properties which can throw unexpected exceptions like this. 
Wouldn't it be better if all properties would be decorated so that they would return None instead of throwing Exceptions?

**Comment by Michael-E-Rose** [comment]
This is the json that Scopus returns:
``````
