### ISSUE TITLE
Abstract description is not beeing extracted

### ISSUE THREAD

**Issue by gaussit** [scopus-api/scopus#32]
Even if an abstract is present in the original scopus .json file, `abstract.description` call is not working and returns `None`, even though a **manual** API call _does_ contain information in the ` dc:description` part. 
Since the abstract class parses the description (` self.description = get_encoded_text(coredata, 'dc:description')`), there must be soemthing wrong with the parser.

I am just using a random article as an example:

```
from scopus.scopus_api import ScopusAbstract

ab = ScopusAbstract('2-s2.0-84871396493', refresh=True)
print(ab.description)
print(ab.doi)
```

Link to abstract:
[https://bmcinfectdis.biomedcentral.com/articles/10.1186/1471-2334-12-366](url)

**Comment by jkitchin** [comment]
In the specific example you gave, this is the xml I get. It has no description or doi in it. Also, the doi.org link seems to point to a totally different article.

<?xml version="1.0" encoding="UTF-8"?><abstracts-retrieval-response xmlns="http://www.elsevier.com/xml/svapi/abstract/dtd" xmlns:ait="http://www.elsevier.com/xml/ani/ait" xmlns:ce="http://www.elsevier.com/xml/ani/common" xmlns:cto="http://www.elsevier.com/xml/cto/dtd" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:prism="http://prismstandard.org/namespaces/basic/2.0/" xmlns:xocs="http://www.elsevier.com/xml/xocs/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><coredata><prism:url>http://api.elsevier.com/content/abstract/scopus_id/0021302936</prism:url><dc:identifier>SCOPUS_ID:0021302936</dc:identifier><eid>2-s2.0-0021302936</eid><dc:title>QUANTUM-MECHANICAL COMPUTERS.</dc:title><prism:aggregationType>Conference Proceeding</prism:aggregationType><srctype>p</srctype><citedby-count>1</citedby-count><dc:publisher>Optical Soc of AmericaWashington, DC, USA</dc:publisher><source-id>131583</source-id><prism:startingPage>50</prism:startingPage><prism:coverDate>1984-01-01</prism:coverDate><dc:creator><author auid="6508146004" seq="1"><ce:initials>Richard P.</ce:initials><ce:indexed-name>Feynman Richard P.</ce:indexed-name><ce:surname>Feynman</ce:surname><preferred-name><ce:initials>R.P.</ce:initials><ce:indexed-name>Feynman R.</ce:indexed-name><ce:surname>Feynman</ce:surname><ce:given-name>Richard P.</ce:given-name></preferred-name><author-url>http://api.elsevier.com/content/author/author_id/6508146004</author-url></author></dc:creator><link href="http://api.elsevier.com/content/abstract/scopus_id/0021302936" rel="self"/><link href="https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&amp;scp=0021302936&amp;origin=inward" rel="scopus"/><link href="https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&amp;scp=0021302936&amp;origin=inward" rel="scopus-citedby"/></coredata><authors><author auid="6508146004" seq="1"><ce:initials>Richard P.</ce:initials><ce:indexed-name>Feynman Richard P.</ce:indexed-name><ce:surname>Feynman</ce:surname><preferred-name><ce:initials>R.P.</ce:initials><ce:indexed-name>Feynman R.</ce:indexed-name><ce:surname>Feynman</ce:surname><ce:given-name>Richard P.</ce:given-name></preferred-name><author-url>http://api.elsevier.com/content/author/author_id/6508146004</author-url></author></authors></abstracts-retrieval-response>

**Comment by gaussit** [comment]
Mea culpa. I mixed that up... 
I have updated the original post with correctly linked abstract id and doi.
Now it should work as intended.

**Comment by jkitchin** [comment]
Can you try the issue-32 branch and let me know if that resolves the issue? If it does, I can merge it into the master branch.

**Comment by gaussit** [comment]
I tried the mentioned issue-32 branch with the exact same article - but there was no abstract/ description provided either.
