### ISSUE TITLE
get_coauthors() throwing UnicodeEncodeError

### ISSUE THREAD

**Issue by mattgittings** [scopus-api/scopus#33]
When trying to get coauthors from an author, I receive the following exception:

```
line 232, in get_coauthors
    coauthor_name = '{0} {1}'.format(given_name, surname)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 2: ordinal not in range(128)

```
(I couldn't wait so I fixed this locally on my machine by simply encoding the given name and surname as UTF-8 at line 232)

**Comment by jkitchin** [comment]
Can you provide a short script that causes this error?

**Comment by mattgittings** [comment]
Yes - though I've just left town for the weekend. Will get to this Monday.

**Comment by mattgittings** [comment]
I'm currently being throttled for too many requests so I can't test this unfortunately, though something like this was causing the exception for me before:

from scopus.scopus_author import ScopusAuthor
author = ScopusAuthor(25935090600)
print [a.name for a in author.get_coauthors()]

**Comment by jkitchin** [comment]
I wonder it that is a python 2 issue. This worked fine for me with python3.

**Comment by mattgittings** [comment]
This is quite likely, as I'm using Python 2, and I believe there are some differences in how strings are handled between the two.

**Comment by Michael-E-Rose** [comment]
Indeed there are differences.  But the fix is simple (though hard to find): Simply make the concatenated name of the coauthors a unicode object.
