### ISSUE TITLE
The difference between request results and the information on the Scopus page

### ISSUE THREAD

**Issue by rogovich** [scopus-api/scopus#34]
Hello! 
I've occasionally noticed the following issue and so far did not find this topic been addressed. There is a divergence between results of the request and the actual information on the author's page.

E.g.  I have the following output 

au = ScopusAuthor("7004130277", refresh = True)
print (au.name)
print (au._current_affiliation)
print (au.ndocuments)
print (au.ncitations)
print (au.ncited_by)

Annamária R. Várkonyi -Kóczy
Selye Janos University, Department of Mathematics and Computer Science
164
494
364

When according to the author's page https://www.scopus.com/authid/detail.uri?authorId=7004130277
it should be 
Annamária R. Várkonyi -Kóczy
Selye Janos University, Department of Mathematics and Computer Science
169
608
435

I had the suspicion that it counts only first-author paper, but it did not hold. May you please help me either by explaining why it happens or what I am missing.

Thanks! Tanya

**Comment by jkitchin** [comment]
That is not too surprising. Believe it or not I think the web version uses a different database than the API. http://kitchingroup.cheme.cmu.edu/blog/2015/04/03/Getting-data-from-the-Scopus-API/

**Comment by rogovich** [comment]
Thank you for the prompt answer! Now it makes some sense.

**Comment by rogovich** [comment]
Just a follow up. We crawled the same database today and week ago. And today we got 4778 publications for the same set of authors, and week ago we got 4708. It's very unlikely that we got actual new publications in this timeframe. Could it be the database to which API refers is dynamic somehow, or that get_document_eids request may return different set of entries for different runs? So it seems that for people with a small number of publication it is more or less stable, but it goes crazy for people who have a lot.

**Comment by Michael-E-Rose** [comment]
It might be results of a couple of backfills they are undertaking (i.e. older volumes being inserted) or the result of mergers of duplicate author profiles.  Duplicates are more likely with authors having a lot of publications, meaning mergers affect those researchers more.

`.get_document_eids()` however returns the same publications as you would get through an advanced Scopus search.
