### ISSUE TITLE
Cache filenames too long

### ISSUE THREAD

**Issue by juanfcocontreras** [scopus-api/scopus#39]
When the query is too long, the module fails when saving cache results:

`[Errno 63] File name too long`

The issue is in `scopus_search.py`:
```
qfile = os.path.join(SCOPUS_SEARCH_DIR,
                             # We need to remove / in a DOI here so we can save
                             # it as a file.
                             query.replace('/', '_slash_'))
```
[...]
```
with open(qfile, 'wb') as f:
```

Could the cache filename be shortened, or at least, truncated?

**Comment by Michael-E-Rose** [comment]
Thanks for the catch!  I guess this is the same as in #6.

I think the best is to not cache the search (i.e. not create a file at all).  Otherwise there is no way recovering the search from a truncated filename.

In the meantime I close this one as duplicate and come up with a solution in the next few days.

**Comment by juanfcocontreras** [comment]
I think that a hash approach should be considered.

In my case, the complex search also involves a long result and the cache mechanism is very handy. The probability of collision in long searches should be very low.

Anyway, I think a parameter to control the creation or not of cache result is always useful.

Thanks!

**Comment by Michael-E-Rose** [comment]
A hash approach is actually a very good idea! Would you be able to contribute? This would be most wonderful!

Regarding the create file-parameter I think it might clash with the logic of the refresh parameter.

**Comment by juanfcocontreras** [comment]
Sure, here it is:

https://github.com/scopus-api/scopus/pull/40

Thanks!
