### ISSUE TITLE
egg_info error on installing scopus

### ISSUE THREAD

**Issue by darjusp** [scopus-api/scopus#41]
Hi guys,

got this one when trying to install scopus with pip (pip install scopus). There are more lines of error but these ones the last ones, not sure if its worth posting everything
```
....
 File "/Users/USERNAME/anaconda/lib/python3.5/locale.py", line 486, in _parse_localename
        raise ValueError('unknown locale: %s' % localename)
    ValueError: unknown locale: UTF-8
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/__/rw3vn8f92zb6mfxw07hzvcnm015yc9/T/pip-build-j1jx4iyv/scopus/ 
```
I'm using python 3.6 with Anaconda. What could be possible solution to that?

**Comment by Michael-E-Rose** [comment]
Thanks for the catch.  I am not 100% sure that this is a scopus-related bug.

Are you on Mac OS?  If so, please try the solution propsed [here](https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7).

If not: Do you have similar problems installing other packages?

**Comment by darjusp** [comment]
Thanks a lot for prompt reply. Indeed i am using Mac OS, and this line worked like a charm:
`export LC_ALL=en_US.UTF-8`
Now scopus works.
Cheers

**Comment by Michael-E-Rose** [comment]
Pleasure!  Hope you enjoy working with scopus.
