### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by varputa** [scopus-api/scopus#42]
Hi, I am using Mac OS X 10 and python 2.7. I have created my api key in the required file. However, I always get this error:

>>> from scopus.scopus_api import ScopusAbstract
>>> ab = ScopusAbstract("2-s2.0-84930616647", refresh=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/scopus/scopus_api.py", line 244, in __init__
    sl = coredata.find('dtd:link[@rel="scopus"]', ns).get('href')
AttributeError: 'NoneType' object has no attribute 'find'

Look forward to your reply. Thanks a lot.

**Comment by Michael-E-Rose** [comment]
Yes I saw it too.  They changed something in the strcture of the xml file.  I am working on it and a fix should be live withing the hour.

**Comment by Michael-E-Rose** [comment]
Fixed in 640f98ab8f9b58fa1b9308448c4d41d76216616e.

Version 0.3.1 is live on PyPI.
