### ISSUE TITLE
Error with ScopusAbstract

### ISSUE THREAD

**Issue by rogovich** [scopus-api/scopus#43]
Dear All,

ScopusAbstract requests just stopped working for me overnight (it's not a quota issue).

E.g. for the query from the readme I get this error.

```
from scopus.scopus_api import ScopusAbstract
ab = ScopusAbstract("2-s2.0-84930616647", refresh=True)
print(ab)
```

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-21-8c32dbaf061a> in <module>()
>       1 from scopus.scopus_api import ScopusAbstract
>       2 
> ----> 3 ab = ScopusAbstract("2-s2.0-84930616647", refresh=True)
>       4 print(ab)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\scopus\scopus_api.py in __init__(self, EID, view, refresh)
>     221         self.creator = get_encoded_text(coredata, 'dc:creator')
>     222         self.description = get_encoded_text(coredata, 'dc:description')
> --> 223         sl = coredata.find('dtd:link[@rel="scopus"]', ns).get('href')
>     224         self_link = coredata.find('dtd:link[@rel="self"]', ns).get('href')
>     225         cite_link = coredata.find('dtd:link[@rel="cited-by"]', ns)
> 
> AttributeError: 'NoneType' object has no attribute 'find'

It happens to all other ScopusAbstract queries as well. I would really appreciate your advice.

Best, Tatiana

**Comment by Michael-E-Rose** [comment]
[duplicate to #42]

Hi there! They seem to have changed the structure of Abstract views yesterday.  A patch is live in scopus-0.3.1. Please upgrade your scopus installation, this should fix the error.  You eventually need to refresh a lot of abstract views as well.

Best,
Michael

**Comment by rogovich** [comment]
Dear Michael, 
sorry for not noticing a duplicate. Thank you!
