### ISSUE TITLE
raw_input error on python3

### ISSUE THREAD

**Issue by lukedickens** [scopus-api/scopus#45]
Hi,

I installed the package pip under python3 but it throws an error on raw_input. I suspect that was because I didn't have the MY_API_KEY specified, but on python3 the call should be input not raw_input.
Thanks,
Luke

**Comment by Michael-E-Rose** [comment]
Hi & thanks for the issue. Which version are you on?

```
import scopus
print(scopus.__version__)
```

**Comment by lukedickens** [comment]
Hi Michael,

It shows 0.4.1 . I should add that having properly set the MY_API_KEY the functionality now works. I just thought you'd appreciate knowing the error I got before things were set up properly. I tried to get the error, but I can't seem to find it.

Best,
Luke
