### ISSUE TITLE
can't get scopus API working for ScopusAbstract

### ISSUE THREAD

**Issue by computron** [scopus-api/scopus#46]
Hi,

I installed scopus-api both in Python 2 and Python 3 environments (Mac), set up my API key as instructed, but can't seem to get the basic Scopus Abstract function working:

```
>>> ab = ScopusAbstract("2-s2.0-84930616647", refresh=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajain/miniconda3/envs/py3/lib/python3.5/site-packages/scopus/scopus_api.py", line 239, in __init__
    self.scopus_link = coredata.find('link[@rel="scopus"]', ns).get('href')
AttributeError: 'NoneType' object has no attribute 'find'
```

Note that the ScopusAuthor seems to work fine, hopefully suggesting that my API key set up should be in place:

```
>>> au = ScopusAuthor(7004212771)
>>> from scopus.scopus_author import ScopusAuthor
>>> au = ScopusAuthor(7004212771)
>>> print([a.name for a in au.get_coauthors()])
['Jens Kehlet Nørskov', 'Bruce C. Gates', 'Matthias Scheffler', 'Dionisios G. Vlachos', 'R. J. Gorte',  ...]
```

**Comment by computron** [comment]
(forgot to add the imports above, but there is a ```from scopus.scopus_api import ScopusAbstract``` preceding the first example and ```from scopus.scopus_author import ScopusAuthor``` preceding the second one - just as in the docs)

**Comment by Michael-E-Rose** [comment]
Hi and thanks for the issue.  They changed some namespace definitions.  I am currently working a fix that works for both the old versions and the new versions.  Should be live within the next two hours.

**Comment by Michael-E-Rose** [comment]
Fixed with df2c8936a3f0aa7896f2ae8fcafe9ef8f8edd183.

**Comment by computron** [comment]
(works for me too, thanks for the quick turnaround!)

**Comment by Michael-E-Rose** [comment]
You're welcome! You can leave a star to show your appreciation :)
