### ISSUE TITLE
scopus.utils not found

### ISSUE THREAD

**Issue by sacrophyte** [scopus-api/scopus#50]
This will probably be a really newbie question, and for that I apologize. I am just starting with python on Windows and hitting a lot of speedbumps. :) Running Anaconda 3, and I already have my environment set to use the scopus libraries. When I change directory to where scopus_api.py is and try to run it, I get an error:

`(C:\Users\schultz\Anaconda3\envs\scopus) C:\Users\schultz\scopus>scopus_api.py
Traceback (most recent call last):
  File "C:\Users\schultz\scopus\scopus_api.py", line 5, in <module>
    from scopus.utils import get_content, get_encoded_text, ns
ImportError: No module named scopus.utils`

**Comment by sacrophyte** [comment]
I have been trying a bunch of different things. Finally I ran this which seems to find everything needed, but I have no clue why I had to do this:

(C:\Users\schultz\Anaconda3\envs\scopus) C:\Users\schultz\Anaconda3\envs>set PYTHONPATH=C:\Users\schultz\Anaconda3\envs\scopus\Lib\site-packages\pip\_vendor

(C:\Users\schultz\Anaconda3\envs\scopus) C:\Users\schultz\Anaconda3\envs>python -m scopus.Lib.site-packages.scopus.scopus_api.py

**Comment by Michael-E-Rose** [comment]
Yes that is a standard thing that Windows users have to do, unfortunatly.  It's to tell python where to look when there are relative imports.  `scopus.utils` is such a thing: It wants to import the submodule `utils` in "folder" `scopus`.

**Comment by sacrophyte** [comment]
Thanks. I am still very confused, though. For instance, now I am trying to run some verification tests, but I cannot find test_ScopusAbstract.py at all - it is not on my harddrive at all. Is it possible that when I installed scopus using an older commit point that I did not pick up the tests directory?

**Comment by Michael-E-Rose** [comment]
These tests are only in the repo and not part of the installation package.  You don't need them to run scopus.

If you want to have them, the easiest way is this: Fork the repo and clone the fork on your computer.   But since you are on version 2.1 now (I reckon) they will likely fail.

**Comment by sacrophyte** [comment]
I apologize for coming back to this, but I am having a headache trying to wrap my head around this. So I closed down Anaconda, and after coming back to it later in the day, I see that the "pip_vendor" directory is gone, and thus the "requests" module can no longer be found. I don't understand why it was even in the pip_directory to begin with (see where I set PYTHONPATH above). Again, I realize this is probably really basic Python stuff and not specific to scopus, and I apologize.

`(C:\Users\schultz\Anaconda3\envs\scopus) C:\Users\schultz\Anaconda3\envs\scopus\Lib\site-packages>dir
 Volume in drive C has no label.
 Volume Serial Number is 5E3B-8AC6

 Directory of C:\Users\schultz\Anaconda3\envs\scopus\Lib\site-packages

09/04/2017  06:58 AM    <DIR>          .
09/04/2017  06:58 AM    <DIR>          ..
09/02/2017  03:13 PM    <DIR>          clock-0.1.dist-info
09/02/2017  03:13 PM             2,073 clock.py
09/04/2017  06:58 AM    <DIR>          cycler-0.10.0.dist-info
09/04/2017  06:58 AM            15,959 cycler.py
09/04/2017  06:58 AM    <DIR>          dateutil
09/02/2017  03:12 PM                 0 easy-install.pth
09/04/2017  06:58 AM    <DIR>          matplotlib
09/04/2017  06:57 AM               570 matplotlib-2.0.2-py3.6-nspkg.pth
09/04/2017  06:59 AM    <DIR>          matplotlib-2.0.2.dist-info
09/04/2017  06:59 AM    <DIR>          mpl_toolkits
09/03/2017  04:26 PM    <DIR>          nose
09/03/2017  04:26 PM    <DIR>          nose-1.3.7.dist-info
09/04/2017  06:58 AM    <DIR>          numpy
09/04/2017  06:58 AM    <DIR>          numpy-1.13.1.dist-info
09/02/2017  03:11 PM    <DIR>          pip
09/02/2017  03:11 PM    <DIR>          pip-9.0.1-py3.6.egg-info
09/04/2017  06:57 AM                90 pylab.py
09/04/2017  06:58 AM    <DIR>          pyparsing-2.2.0.dist-info
09/04/2017  06:58 AM           231,039 pyparsing.py
09/04/2017  06:58 AM    <DIR>          python_dateutil-2.6.1.dist-info
09/02/2017  03:13 PM    <DIR>          pytz
09/02/2017  03:13 PM    <DIR>          pytz-2017.2.dist-info
07/07/2017  10:33 PM               119 README.txt
09/04/2017  12:51 PM    <DIR>          scopus
09/03/2017  04:31 PM    <DIR>          scopus-0.2.1-py3.6.egg-info
12/23/2016  02:19 PM           763,314 setuptools-27.2.0-py3.6.egg
12/23/2016  02:19 PM                31 setuptools.pth
09/04/2017  06:58 AM    <DIR>          six-1.10.0.dist-info
09/04/2017  06:58 AM            30,098 six.py
09/02/2017  03:13 PM    <DIR>          tzlocal
09/02/2017  03:13 PM    <DIR>          tzlocal-1.4.dist-info
09/02/2017  03:11 PM    <DIR>          wheel
09/02/2017  03:11 PM    <DIR>          wheel-0.29.0-py3.6.egg-info
09/04/2017  06:59 AM    <DIR>          __pycache__
              10 File(s)      1,043,293 bytes
              26 Dir(s)  10,353,676,288 bytes free`

**Comment by sacrophyte** [comment]
partially resolved: I see that pip_vendor is now pip\_vendor (which still makes absolutely no sense to me). I keep thinking "there has got to be a better way to do this!" *grin*

**Comment by Michael-E-Rose** [comment]
Since I never worked with Python on Windows nor with anaconda I really cannot help you on this.  My suggestion would be to go without anaconda and install Python 3.5 without editor (i.e. IDLE) and write in script mode instead.
