### ISSUE TITLE
error from ScopusSearch

### ISSUE THREAD

**Issue by sacrophyte** [scopus-api/scopus#51]
Good day,

I am starting a python script which will eventually map given authors to a list of author-ids. To start with, I am attempting a somewhat simple search on a known author, but I receive an error:

**map_authors.py**
`from scopus import ScopusSearch

s = ScopusSearch('AUTHFIRST ( Bo ) and AUTHLASTNAME ( Li ) and AFFIL ( University of Illinois )', refresh=True)
print(s)`

`(C:\Users\sac\AppData\Local\Continuum\Anaconda3\envs\scopus) c:\Users\sac\scopus_base>python map_authors.py
Traceback (most recent call last):
  File "map_authors.py", line 4, in <module>
    print(s)
  File "C:\Users\sac\AppData\Local\Continuum\Anaconda3\envs\scopus\lib\site-packages\scopus\scopus_search.py", line 110, in __str__
    entries='\n    '.join(self.EIDS))
KeyError: 'query'`

The error does not seem to map back to the Scopus Search API known errors. What is the root issue?

**Comment by Michael-E-Rose** [comment]
I have no troubles with the current version (0.4.3).  What version are you on?

To find out, type
```
import scopus
print(scopus.__version__)
```

**Comment by sacrophyte** [comment]
You had me use a previous commit due to the incompatibility of pbr with Windows. I lbelieve it is 0.2.11

`>>> import scopus
>>> print(scopus.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scopus' has no attribute '__version__'`

**Comment by Michael-E-Rose** [comment]
Well then there is little I can regarding this issue because it is already fixed in later versions.

I just tried scopus version 0.2.1 (use `pip -I install scopus==0.2.1`) and it works just fine:

```
>>> s = ScopusSearch('AUTHFIRST ( Bo ) and AUTHLASTNAME ( Li ) and AFFIL ( University of Illinois )', refresh=True)
>>> s
<scopus.scopus_search.ScopusSearch object at 0x7f772df62190>
>>> print(s)
AUTHFIRST ( Bo ) and AUTHLASTNAME ( Li ) and AFFIL ( University of Illinois )
        Resulted in 0 hits.
```

PS: It is `.__version__`, not `.version`.
