### ISSUE TITLE
ISSN and E-ISSN for abstracts

### ISSUE THREAD

**Issue by rogovich** [scopus-api/scopus#52]
Dear all,

we are dealing with a massive dataset and need ISSN's for the further matching. For journals that have both issn and e-issn, request ScopusAbstract('').issn returns two values, e.g.:
'09670750 14680351'

I just want to make sure that in this pair ISSN is _always_ the first one? 

Thank you!

**Comment by Michael-E-Rose** [comment]
Yes it is, although it is totally up to Scopus to do this.  I will update the documentation accordingly.  Thanks for bringing this to my attention!

**Comment by rogovich** [comment]
Dear Michael,
so we did the mining and unfortunately it is not the case, e.g. look for this two publications (i've copied issn/e-issn pairs as their appear on the journals' pages in Scopus:

`## ISSN:0340-8744 E-ISSN:1573-6911
print(ScopusAbstract('2-s2.0-85018319134', refresh = True).issn)`
[Out]: 15736911 03408744

`## ISSN:0967-0750 E-ISSN:1468-0351
print(ScopusAbstract('2-s2.0-83855160827', refresh = True).issn)`
[Out]: 09670750 14680351

So, I guess for now there is now way around it?

**Comment by Michael-E-Rose** [comment]
I am afraid there is no way around.

When you look at http://api.elsevier.com/content/abstract/eid/2-s2.0-85018319134?APIKey=ENTERYOURKEYHERE you see the following line: `<prism:issn>15736911 03408744</prism:issn>`.  That's where `ScopusAbstract()` gets its information from.  It's really up to Scopus how they sort the ISSN, and I am really not surprised that they are not consistent.

**Comment by Michael-E-Rose** [comment]
Docstring updated with fadbe55211b6aa0c6ab89b8c39061cdc8823695a, going live with `0.5.0`.

**Comment by james-geiger** [comment]
@Michael-E-Rose With the full view, Scopus now provides these in separate fields, so we could return a named tuple with the ISSN value and types.

I have the working on my machine and would be happy to submit a PR.

**Comment by Michael-E-Rose** [comment]
And I would be happy to accept it!

**Comment by Michael-E-Rose** [comment]
I refactored this again, and it will go live with the next release:

```
print(AbstractRetrieval('2-s2.0-85166620539').issn)
# ISSN(print='09318658', electronic=None)
print(AbstractRetrieval('2-s2.0-85166620539', view="FULL").issn)
# ISSN(print='09318658', electronic=None)
print(AbstractRetrieval('2-s2.0-85166620539', view="META").issn)
# ISSN(print='09318658', electronic=None)
print(AbstractRetrieval('2-s2.0-85018319134').issn)
# None
print(AbstractRetrieval('2-s2.0-85018319134', view="FULL").issn)
# ISSN(print='03408744', electronic='15736911')
print(AbstractRetrieval('2-s2.0-85018319134', view="META").issn)
# None
print(AbstractRetrieval('2-s2.0-83855160827').issn)
# None
print(AbstractRetrieval('2-s2.0-83855160827', view="FULL").issn)
# ISSN(print='09670750', electronic='14680351')
print(AbstractRetrieval('2-s2.0-83855160827', view="META").issn)
# None
```

Basically, always return a namedtuple even when one entry is `None`, unless pybliometrics cannot distinguish the two (which is the case for any view other than "FULL" and given that the E-ISSN exists).
