### ISSUE TITLE
Scopus Api Error

### ISSUE THREAD

**Issue by Stawliner** [scopus-api/scopus#54]
Dear Michael-E-Rose, dear programmers,
 
I am using your Scopus Api and I like several aspects of it. But when I create an instance of the class "ScopusAbstract(object)" (in scopus_api.py), inserting an EID like "2-s2.0-63449122615" as string object, I get the error "NoneType object has no attribute 'find'". The specific problem is in line 244, which is 
 
`self.scopus_link = coredata.find('link[@rel="scopus"]', ns).get('href')` 

Would you be so kind and help me? I really need this for my study course.
 
Here is an example call:
 
```
from scopus.scopus_api import ScopusAbstract
from scopus.scopus_search import ScopusSearch
 
query_str = "This paper presents a new approach to select events of interest to users in a social"
query = ScopusSearch("ABS({})".format(query_str), refresh=False)
id = query.EIDS[0]
ab = ScopusAbstract(id)

``` 
-> `Error "NoneType object has no attribute 'find'" in line 244 of scopus_api.py`
 
Thank you.

Kind regards

Stefan Wilharm

**Comment by Michael-E-Rose** [comment]
Hi Stefan! Which version are you on? Check with

```
import scopus
print(scopus.__version__)
```

**Comment by Stawliner** [comment]
Hi! My version is 0.3.1. I already tried to update via "pip install scopus", but it says "Req. already satisfied".

**Comment by Michael-E-Rose** [comment]
You need to update with the `--upgrade` flag.

**Comment by Stawliner** [comment]
Ah now it works! It is great you made an update. Thank you so much for your fast help!

**Comment by Michael-E-Rose** [comment]
You're very welcome!  You can leave a star (on the top right) corner to show your appreciation, if you like.

Best,
Michael

**Comment by Stawliner** [comment]
Thank you! I left you a star. Have a good time!
