### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by BigPyQuant** [scopus-api/scopus#55]
Got this error 
401 Client Error: Unauthorized for url: http://api.elsevier.com/content/author/author_id/7004212771?author_id=7004212771&view=ENHANCED

Here's my code:

import scopus
scopus.ScopusAuthor(7004212771)

I have modified my_scopus.py to add MY_API_KEY 
I have an Insti token as well. Not sure how to fit that. thanks!

**Comment by BigPyQuant** [comment]
another
HTTPError: 401 Client Error: Unauthorized for url: http://api.elsevier.com/content/search/scopus?count=0&query=FIRSTAUTH+%28+kitchin+j.r.+%29&start=0&field=eid

CODE:

ab = ScopusAbstract("2-s2.0-84930616647", refresh=True)

how do you add my API KEY to end of eid?

**Comment by jkitchin** [comment]
You may not have access to Scopus. You need a license to access it, and that is usually through your institution.

**Comment by Michael-E-Rose** [comment]
See also https://scopus.readthedocs.io/en/latest/tips.html#error-messages:

> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url
Either the provided key is not correct, in which case you should change it in ~/.scopus/my_scopus.py, or you are outside the network that provides you access to the Scopus database (e.g. your university network). Remember that you need both to access Scopus.
