### ISSUE TITLE
Elsevier Announcement 

### ISSUE THREAD

**Issue by AymericBds** [scopus-api/scopus#56]
Hi,

In the website for developpers, Elsevier announces the end of the object "Search API". 
" Please note: Object Search API will no longer be available after October 2017. "
Is it the same that "Scopus Search"?
Do you know what's next?

We have developped a new methology to identify collaboration cluster in our university. But we need access to Scopus data for authors and documents.

Thanks a lot

Aymeric

**Comment by Michael-E-Rose** [comment]
Hi and thanks for letting us know! This is very valuable information.  I will have a look into this.

**Comment by AymericBds** [comment]
Hi,

I have a response from Elsevier support : 
" No; that's not the same API.
 
The Object Search API searches for images, tables and such things in ScienceDirect article database, based on some search criteria. There's a handful of users using that API, it's a very obsolete thing, and we're discontinuing it because Elsevier is not going to maintain that search index anymore. This won't impact you in any way.
 
We wouldn't dream of getting rid of Scopus Search API ... "

Everything is fine! No problem.

Sorry 

Aymeric

**Comment by Michael-E-Rose** [comment]
Thanks for finding this out and letting us know, Aymeric!
