### ISSUE TITLE
https and instToken

### ISSUE THREAD

**Issue by AymericBds** [scopus-api/scopus#59]
Hey,

Everytime I update the module Scopus, I have problems.
Indeed, Elsevier gave me APIkey and **InstToken** to access to API Scopus.
Elsevier told me to use **https** and not http.

Everytime I need to check code to detect some modifications...

And now, with the new update (citation Overview), I try to detect where is wrong...

Can you add the option of instToken (it's easy) and (more) the HTTPS url ?

Thanks a lot for your help

Aymeric

**Comment by Michael-E-Rose** [comment]
Hi Aymeric!  Sorry to hear of this problem, I wasn't aware of this.
Changing to https if easy, of course.  But I don't know how the instToken device works.  Can you let me know the code you usually use after a scopus update?

Best,
Michael

**Comment by AymericBds** [comment]
Hi Michael,

Thanks for your help.
Add InstToken, it's easy : 
In get_content.py, I add line like "token = my_scopus.MY_TOKEN" in _download_ and _get_content_ functions. (I don't use _load_api_key_) .

For https, it's not easy as it looks because you have to change the url you have imported (and sometimes you don't know if it's http or https).

When I update scopus code, I try to remember where I've modified to reproduce modifications...

Thanks 

Aymeric

**Comment by Michael-E-Rose** [comment]
Hi Aymeric, I finally have time for this.  Could you please show me how exactly you manipulate the functions?  You can paste the entire code in here.  The difficulty I'm having is to accomodate both problems.

The URL manipulation to use https instead of https seems to be the smaller problem.

**Comment by AymericBds** [comment]
Hi Michael,

For https & Insstoken, I found a solution : In get_content.py , I have added some elements in download function line 45 : 
``try:
		key = my_scopus.MY_API_KEY
		**token = my_scopus.MY_TOKEN**
    except AttributeError:
        #load_api_key()
		key = my_scopus.MY_API_KEY
		**token = my_scopus.MY_TOKEN**
    header = {'Accept': 'application/{}'.format(accept), 'X-ELS-APIKey': key,'X-ELS-Insttoken': token}
resp = requests.get(url=**url.replace('http:','https:')**, headers=header, params=params)
    resp.raise_for_status()
    return resp "

Now, I don't use load_api_key function.

I hope that's what you expected

Aymeric

**Comment by Michael-E-Rose** [comment]
Thanks, that should get me started.  I will now have to think about how to merge both approaches and hope to something by the end of next week.

The https problem has been solved in 0f046d86cea0018ea6a1e52aab42cca3475f580d.  According to Elsevier, they are moving to https soon anyways.

**Comment by Michael-E-Rose** [comment]
Hi @AymericBds! Here is a solution for InstToken readers: Create a file in `~/.scopus/config` which stores both your API Key and your InstToken.  Format is described [here](https://github.com/scopus-api/scopus/blob/InstToken/docs/configuration.rst).

Would you please give it a try and report how it works?  The commit is live but not in the master branch.  Therefore please install with `pip install git+https://github.com/scopus-api/scopus.git@InstToken`. You would greatly help us!

For future readers: Do not create this file unless you want/have to use token-based authentication. In future releases I plan to store all credentials in there.

**Comment by AymericBds** [comment]
Hi @Michael-E-Rose , thanks for your help.

I work with this solution (the file containing APIkey and InstToken) for several months now. It is working good.

Thanks

**Comment by Michael-E-Rose** [comment]
Thanks for the reply, it's very good you can assist on this. What do you mean by several months? I created the branch last Friday? Could you follow the instructions regarding the config file?

**Comment by jupotratz** [comment]
How to get insttokken  in My API?

**Comment by Michael-E-Rose** [comment]
Insert a section like 
```
[InstToken]
X-ELS-APIKey = XXX
X-ELS-Insttoken = PPP
```
in your `config.ini`, see https://pybliometrics.readthedocs.io/en/stable/configuration.html.

**Comment by fa00fa** [comment]
> How to get insttokken in My API?

are you resolve it, can you tell me method?

**Comment by Michael-E-Rose** [comment]
@fa00fa see my latest answer
