### ISSUE TITLE
issue with creating qfile for complex scopus queries

### ISSUE THREAD

**Issue by Wasala** [scopus-api/scopus#6]
When you have complex (and long) scopus queries, the qfile creation mechanism fails. For example, for the search query "test" (with double quotes). Rather than just replacing slashes of the queries (query.replace('/', '_slash_') in scopus_search.py how about implementing a solution like the one mentioned here (see the accepted solution): http://stackoverflow.com/questions/7406102/create-sane-safe-filename-from-any-unsafe-string
Then again, when the query is very long, this will still generate a very long file name. Therefore may be it's better to hash the query string and use the hash to create the file.

**Comment by jkitchin** [comment]
The hash is probably the best approach. Any chance you want to do it and make a pull request?

**Comment by Wasala** [comment]
also noticed a few more issues, might work on these  as and when i have time :)

**Comment by Michael-E-Rose** [comment]
PR #40 will solve this issue.

**Comment by Michael-E-Rose** [comment]
This change has gone live with scopus 1.0 (b7f2bcb9bca3777b2bb7fb6f272865188933b5a9) on Saturday.
