### ISSUE TITLE
ScopusAbstract references

### ISSUE THREAD

**Issue by varputa** [scopus-api/scopus#60]
Hi Michael,

I try to use ScopusAbstract to get references(environment: python 3, MAC OS). The code looks like the following:

from scopus import ScopusAbstract
ab = ScopusAbstract("2-s2.0-84930616647")
print(ab.refcount)
print(ab.references)

It returns "None". Other attributes work well, like ab. volume, ab. authors. Could you help me with this? 

Thanks a lot,
Chao

**Comment by Michael-E-Rose** [comment]
Yes, you need to load the abstract with `ab = ScopusAbstract("2-s2.0-84930616647", view='FULL')`. `ScopusAbstract` has a couple of views and only a `"FULL"` view will load references.  Unfortunately this means you'd have to refresh all the files you already downloaded. Keep in mind though that Scopus does not not provide references for all items.

I will try to make this more clear in the documentation.

**Comment by varputa** [comment]
Thank you very much!

**Comment by Michael-E-Rose** [comment]
You're welcome! I will keep this one open as a reminder to update documentation soon.
