### ISSUE TITLE
Using the 'fields' parameter of ScopusSearch

### ISSUE THREAD

**Issue by marijane** [scopus-api/scopus#61]
I notice in the documentation that I can specify a list of fields I want returned from ScopusSearch.
https://scopus.readthedocs.io/en/latest/reference/scopus.ScopusSearch.html

What I'm wondering is, after I specify the list, how do I get them out of the results?  Or is this not yet fully implemented?

**Comment by Michael-E-Rose** [comment]
Hi Marijane, thanks for bringing this to my attention.  It looks like an odd parameter: It definitely works in our code, but it has no visible effect on what is returned.  I tested it directly in the browser using the Scopus API with the example specified [here](https://api.elsevier.com/documentation/SCOPUSSearchAPI.wadl).  No matter which value(s) I put in there, the returned information on items is still the same.

I will investigate this further and probably update our documentation.
