### ISSUE TITLE
EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by sofiaalves** [scopus-api/scopus#80]
in this file: scopus/utils/create_config.py 
if py3:

```
key = input(prompt_key)
```

I just created config file with my apiKey but I have this issue: `EOFError: EOF when reading a line`

**Comment by Michael-E-Rose** [comment]
Hi! What was the key like that you put in? Can it be that you accidentally included a quotation mark? If we can't solve we can create the config file manually. Which system are you on?

**Comment by sofiaalves** [comment]
Hi! When I ran the scopus.utils.create_config () command, I inserted the key with no quotes.
The problem is in the input() function within the file: scopus/utils/create_config.py. 
If I replace this code with the value of the key, within quotes in the create_config.py file I no longer have the same error. But says the key is not authorized.

When I installed the scopus library I also had a lot of problems with the directories that are created. It was always saying that I did not have permission to create the directories and I was always creating these directories manually with sudo. I do not know if there might be any conflict with that.

I'm using linux.

Thanks in advance :)

**Comment by Michael-E-Rose** [comment]
The issue with creating directories is a typical rights problem, nothing related to scopus.

The other problem is interesting, though. What line is the error message referring to? Could you post the complete traceback?

Also, you quickly solve your problem: Your config.ini should look like this:
```
[Directories]
AbstractRetrieval = /home/YOURPROFILE/.scopus/abstract_retrieval
AffiliationSearch = /home/YOURPROFILE/.scopus/affiliation_search
AuthorRetrieval = X:\Prof. Harhoff\Harhoff_GENERAL\Data\Bibliometrics\Scopus_API\author_retrieval
AuthorSearch = /home/YOURPROFILE/.scopus/author_search
CitationOverview = /home/YOURPROFILE/.scopus/citation_overview
ContentAffiliationRetrieval = /home/YOURPROFILE/.scopus/affiliation_retrieval
ScopusSearch = /home/YOURPROFILE/.scopus/scopus_search

[Authentication]
APIKey = ...
```

**Comment by Michael-E-Rose** [comment]
So, did that solve your issue @sofiaalves ?
