### ISSUE TITLE
AbstractRetrieval with full view returns no references although the API REF view does

### ISSUE THREAD

**Issue by fabiosangregorio** [scopus-api/scopus#81]
Hi,
I am using the AbstractRetrieval to get the references of a document, using this code:

```python
AbstractRetrieval(paper_id, view="FULL").references
```

but it returns None. 
As stated in the documentation:

> Note: Requires the FULL view of the article. Might be empty even if refcount is positive.

Using Scopus API with a simple get request and the REF view, like this:

```
https://api.elsevier.com/content/abstract/EID:2-s2.0-84951753303?apiKey=MY_API_KEY&view=REF&httpAccept=application/json
```

it returns an array of 40 references (even if the value of `@total-references` field is 48).

Using Scopus API with the FULL view, I get an array of 48 references.

I would expect to get the same results as the FULL view.

**Comment by Michael-E-Rose** [comment]
Did you try refreshing?

It might be that you have downloaded the abstract in another view before, which will then be reused even if you change the view parameter.  That is, the view parameter really only takes effect for new abstracts and for refreshing.

**Comment by fabiosangregorio** [comment]
Thank you very much, refreshing did the trick!

**Comment by Michael-E-Rose** [comment]
You're welcome

**Comment by fabiosangregorio** [comment]
Sorry to bother you again, but the references in the FULL view only return the reference's Authors' name (as intended by the Scopus API), in this fashion:

```json
"ref-authors": {
    author: [{
        "@seq": "1",
        "ce:initials": "M.",
        "@_fa": "true",
        "ce:surname": "Armbrust",
        "ce:indexed-name": "Armbrust M."
    }]
}
```

 I'd need the REF view to get the ids of those authors, which returns:

```json
 "reference": [{
    ...
    "author-list": {"author": [
        {
            "ce:given-name": "Michael",
            "preferred-name": {
                "ce:given-name": "Michael",
                "ce:initials": "M.",
                "ce:surname": "Armbrust",
                "ce:indexed-name": "Armbrust M."
            },
            "@seq": "1",
            "ce:initials": "M.",
            "@_fa": "true",
            "affiliation": {
                "@id": "60025038",
                "@href": "https://api.elsevier.com/content/affiliation/affiliation_id/60025038"
            },
            "ce:surname": "Armbrust",
            "@auid": "35800975300",
            "author-url": "https://api.elsevier.com/content/author/author_id/35800975300",
            "@force-array": "true",
            "ce:indexed-name": "Armbrust M."
        }]
    }
}]
```

Am I missing something?

**Comment by Michael-E-Rose** [comment]
Oh that's interesting! I didn't know the REF view returns information the FULL view doesn't provide.  We need to change the class so that it can handle information from both views.

Do you want to give it a try and create a PR? Otherwise I can have a look into it on Thursday.
