### ISSUE TITLE
ContentAffiliationRetrieval __str__ method AttributeError

### ISSUE THREAD

**Issue by Blake11** [scopus-api/scopus#83]
Method __str__ gives the following error
AttributeError: 'ContentAffiliationRetrieval' object has no attribute 'name'

Atribute was renamed in scopus 1.x and should be
`s = '''{self.affiliation_name} ... '''`
instead of 
`s = '''{self.name} ...'''`

Using:
Windows 10 64bit
scopus.__version__ 1.4.3
python 3.6

**Comment by Michael-E-Rose** [comment]
Thanks for the catch, @Blake11 !
