### ISSUE TITLE
Error from AbstractRetrieval references

### ISSUE THREAD

**Issue by ste210** [scopus-api/scopus#86]
When getting the AbstractRetrieval for 2-s2.0-85028692635 and looking at the references, I get a TypeError. I think it is enough to add TypeError in except of line 20 of utils\parse_content.py".

```
s = scopus.AbstractRetrieval('2-s2.0-85028692635', view='FULL', refresh=True)

s.references
Traceback (most recent call last):

  File "<ipython-input-15-5705d616f366>", line 1, in <module>
    s.references

  File "C:\anaconda3\lib\site-packages\scopus\abstract_retrieval.py", line 383, in references
    items = listify(chained_get(self._json, path, []))

  File "C:\anaconda3\lib\site-packages\scopus\utils\parse_content.py", line 19, in chained_get
    container = container[key]

TypeError: 'NoneType' object is not subscriptable`
```

**Comment by crew102** [comment]
Hey @ste210 ,  `scopus.AbstractRetrieval('2-s2.0-85028692635', view='FULL', refresh=True)` runs fine for me. I'm guessing you're not a Scopus subscriber? Only subscribers can access the the "FULL" view for the abstract retrieval API (https://dev.elsevier.com/api_key_settings.html). Try using `view="META"` and see if that works for you.

**Comment by Michael-E-Rose** [comment]
I also don't get an error - `s.references` is simply empty?

**Comment by ste210** [comment]
Thank you guys, probably my fault.. need to update
