### ISSUE TITLE
switching API key

### ISSUE THREAD

**Issue by ly2019** [scopus-api/scopus#88]
Hi,

I am hoping to switch to another API key because each key comes with a quota. However, even after uninstalling (or deleting) the package, the same old API key was automatically applied after reinstall. Do you know how to switch to another key?

Thank you!

**Comment by Michael-E-Rose** [comment]
Hi @ly2019! You need to change the key manually in the configuration file, see https://scopus.readthedocs.io/en/latest/configuration.html. I'm going to update the documentation to make it more clear.

Let me know if you have troubles finding the file.

Michael

**Comment by ly2019** [comment]
Thank you for your prompt response, Michael! I had a little problem
locating the file. But I will try again.
Lily

Michael E. Rose <notifications@github.com> 于2019年3月13日周三 下午6:37写道：

**Comment by Michael-E-Rose** [comment]
Which Operating System are you on? On a Unix-System (Max, Linux) the `.scopus` folder is in your home directory, but it's hidden.

**Comment by ly2019** [comment]
I located the folder and changed the key. Thank you very much!

**Comment by Michael-E-Rose** [comment]
Sure!
