### ISSUE TITLE
Add ability to query Scopus without downloading records

### ISSUE THREAD

**Issue by crew102** [scopus-api/scopus#89]
I think it'd be useful for `Search` classes to have the ability to just query the Scopus APIs without actually downloading all the data. The user may want to know how many records match their query before actually committing to downloading those records. The way I'd implement this would be to have a `download` parameter added to `Search` classes which is set to `True` by default. When the user just wants to find out how many records match their query, they'd set `download=False`.

Related to this, I'd suggest adding a property for the number of matching records. Adding this property would allow the user to, for example, programmatically decide whether to download the records based on the size of the result set.

Happy to put together a PR for this.

**Comment by Michael-E-Rose** [comment]
This is  a fantastic idea! Looking forward to the PR :) Just don't forget to add the functionality in the tests, please.
