### ISSUE TITLE
Class for citation overview API

### ISSUE THREAD

**Issue by Michael-E-Rose** [scopus-api/scopus#9]
I have recently started using Scopus' [Citation Overview API](http://api.elsevier.com/documentation/AbstractCitationAPI.wadl).  That's a special API to retrieve yearly citations to an author.  That's a necessary add-on because the yearly citation from the Author Retrieval API equals the sum of total citations to all articles published in a given year.  In most cases this is not necessary.

As the Citation Overview API requires special permission (see page), it was probably not implement in this package.  Are you, @jkitchin, interested in adding the class for this API?  I'm happy to create a PR in the next few days.

**Comment by jkitchin** [comment]
I would be happy to take a pull request on this.

**Comment by emtiaz-ahmed** [comment]
Is citation overview API access ready? If not, when will be this feature available? I am interested to use per year citation data. Thank you.

**Comment by Michael-E-Rose** [comment]
It's not ready but it is planned for version 1.0.  I hope to finish it by the end of next month.

**Comment by Michael-E-Rose** [comment]
I am working on this now, @emtiaz-ahmed. Should be done by Monday.

**Comment by Michael-E-Rose** [comment]
The class is live and fully [documented](https://scopus.readthedocs.io/en/latest/reference/scopus.CitationOverview.html) with [examples](https://scopus.readthedocs.io/en/latest/examples/CitationOverview.html).
