### ISSUE TITLE
Misc items re: the httpAccept parameter

### ISSUE THREAD

**Issue by crew102** [scopus-api/scopus#92]
Two misc items related to the parameter that specifies acceptable MIME types (aka the `Accept` header param and `httpAccept` query param). 

1. The `accept` parameter in `download()`/`get_content()` is unnecessary, as we always use the content type of JSON. For example, all classes that inherit from Retrieval and Search have `accept='json'` : 

https://github.com/scopus-api/scopus/blob/260adf18ac65baf507bdf5d0b786f40b0d11836f/scopus/classes/retrieval.py#L75-L76

https://github.com/scopus-api/scopus/blob/260adf18ac65baf507bdf5d0b786f40b0d11836f/scopus/classes/search.py#L98

We're also assuming the text that the API serves is JSON when parsing happens, so it doesn't make sense allow other types to be passed along to `download()`/`get_content()`.

2. Since we always ask the API for JSON, we should make sure that the user knows that they can't pass along the query parameter of `httpAccept` as a keyword arg in Search classes. I suggest that the Search class investigates the args passed along as `**kwds`, and if one of those params is `httpAccept`, a warning is thrown saying that their value for `httpAccept` will be ignored, as JSON is always used.

**Comment by Michael-E-Rose** [comment]
Yes, both issues will be fixed with scopus 2.0.  The old classes parsed xml, which is why there is the parameter to set the MIME type.  It's also correct that the count parameter is exclusively for internal use, so we won't need to parameterize that.  As for the `kwds`, they go into the query, not in the header.  So, setting the MIME type will actually not have an effect.

**Comment by crew102** [comment]
The query params override the header params (https://dev.elsevier.com/documentation/ScopusSearchAPI.wadl), so if the user set `httpAccept` as a keyword arg, the MIME type they chose would be the actual one that the API serves, regardless of what we set as the value in the header.
