### ISSUE TITLE
Pass along detailed error messages to user

### ISSUE THREAD

**Issue by crew102** [scopus-api/scopus#94]
Whenever the API throws an error, the error is described to users of the `scopus` package at the level of the HTTP status code. For example, if I set the value of `count` to 300, the API throws a 400 error (bad request) and the scopus package raises the following exception: `scopus.exception.Scopus400Error('BAD REQUEST for url: https://api.elsevier.com/content/search/scopus')`. However, there is more detailed text that the API is serving about the nature of the error (i.e., the statusText): `{"service-error":{"status":{"statusCode":"INVALID_INPUT","statusText":"Exceeds the maximum number allowed for the service level"}}}`

 It could be helpful to provide users with the more detailed error text that the API is providing.

**Comment by Michael-E-Rose** [comment]
I guess the change has to be made in https://github.com/scopus-api/scopus/blob/master/scopus/utils/get_content.py#L100

The question is: Should we look into the json whenever there is an error message, or just for the 400 Error?  Are all error messages as verbose as in the example?

**Comment by crew102** [comment]
I would suggest looking to the JSON whenever there is an error message. A try statement will attempt to parse the JSON and if it fails, we'll fall back to an error that will just describe the HTTP error code. From what I've seen, the error messages are similar to the example above in how much detail they are providing.

**Comment by Michael-E-Rose** [comment]
So, is the case that whenever there is an error, there is an error message in the same spot?  If so, we should always use that error message but keep the error type (i.e. Scopus400Error).

**Comment by crew102** [comment]
In the same spot meaning the structure of the JSON/XML containing the error message is the same? From what I've seen, yes. And yes, I was thinking we keep the error handing to how it is right now in the package (with the `ScopusExceptions`) but just pass the more detailed error text into these.
