### ISSUE TITLE
Cached results should be based on view type

### ISSUE THREAD

**Issue by fabiosangregorio** [scopus-api/scopus#99]
Hi,
first of all thank you for the continuous development of the package :)

Currently the cached results of the API are shared across all view types, therefore changing the view type with `refresh=False` yields in an incorrect json, which is not only confusing but can result in nasty bugs.

Example (my use case):
```python
paper_refs = AbstractRetrieval("2-s2.0-84951753303", view="REF").references
...
paper_issn = AbstractRetrieval("2-s2.0-84951753303", view="FULL").issn
```
Output:
```python
paper_refs: [<Reference, len() = 16>, <Reference, len() = 16>, ...]
paper_issn: KeyError: 'coredata'
```
And switching the statements:
```python
paper_issn = AbstractRetrieval("2-s2.0-84951753303", view="FULL").issn
...
paper_refs = AbstractRetrieval("2-s2.0-84951753303", view="REF").references
```
Output:
```python
paper_refs: [<Reference, len() = 16>, <Reference, len() = 16>, ...] // these references are different from the REF view, as they should be
paper_issn: '0926227X'
```

Since the cache is extremely valuable in my use case (saves ~60% of API requests) I need to be able to switch views without refreshing the json.

Can the cached jsons from different views be treated as different?

**Comment by Michael-E-Rose** [comment]
Yes, I've been thinking about this issue for a while.

My currently preferred solution is to have different subfolders for each view and cache files there.

I'll think a bit more about it and implement it next week.

**Comment by Michael-E-Rose** [comment]
Related: #81 , #66.

**Comment by Michael-E-Rose** [comment]
Files are cached according to their view in subfolders to the previously existing folders.  The patch will go live with the next major release (i.e. scopus 2.0), somewhen the coming week.  The change affects _all_ classes, even those where only one view is implemented.

If you want to make use of previously cached files, you have to move them:
* `~/abstract_retrieval/` to 
* `~/`
* `~/`
* `~/`

**Comment by fabiosangregorio** [comment]
Thank you so much for the hard, excellent work!
